# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73cd2b704249b74e30489bb512c56cd2ed00cd6be0d15d4a136783560100f0fcc9dd0705954dc6abe749de89ab2aa65ced07e733606cd127f51ffd3ba87dbe0

test:
  secret_key_base: 893845a6c47806c7660e0888aa023aab3934bedb1d7ab0ce4c985cbcb50e8b0771eb5cdb95de5ac96b01c06129f6f17cbf37bae399a0d8e03641a5847ec094eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
